events {}

http {
    upstream auction_api {
        server host.docker.internal:4400;
        server host.docker.internal:4401;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://auction_api;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}